### PR TITLE
rename the rename_to_href function

### PR DESCRIPTION
**Pull request by abdulhaq-e**

### CODE REVIEW

**Comment by jwhitlock** [comment]
Sorry, I don't see why you'd want to do this.

**Comment by abdulhaq-e** [comment]
In commit b00d2db917cdbbe267cfcbdaa7064ef56d09c1db , one of the changes was:

`- Changed "href" to "self" under "links".`

So I thought it would be better to change the function name as well and I saw that the name change has no side effects.

**Comment by jwhitlock** [comment]
OK, that makes sense.  I see that tests are failing, but that's due to early broken merges.  I think fixing tests is the priority over any code cleanup, however, so looking to other maintainers to judge if this is ready to merge.

**Comment by abdulhaq-e** [comment]
I plan to use this in a project so I'm keen to collaborate however I'm no expert coder (especially when it comes to collaboration) so I might have some beginner's questions:

You said that fixing tests is the priority. However, what if the tests themselves are not testing the code to the current standard. For example, the current stable specifications for JSON API states that attributes should be stored in an [attribute](http://jsonapi.org/format/#document-resource-object-attributes) object. The current renderer doesn't do this. So what should the next step be? Fix the tests without modifying the code (i.e. keep the older specifications for now) or modify the code AND fix the tests. Sorry, I'm lost here!

**Comment by jwhitlock** [comment]
This project is in a transition.  It was written against RC2, and significant changes were made to the JSON API spec in 1.0.  In the meantime, the initial contributors have moved on.  In my case, I expect it will be 6-12 months before I think of transitioning my own project to JSON API 1.0.

I believe the 1.0 effort is in PR #31 - you might want to take a look at that branch.

**Comment by erickwilder** [comment]
@jwhitlock 
This is a small change and albeit we're with failing tests, they're not reflecting the current JSON API spec. 
I'm trying to organize myself to go back and look to this project more often and really want to help.

I have the same doubt as @abdulhaq-e: should we start by making tests pass with the current implementation _or_ send new pull requests with 1.0-compliant code ignoring unrelated tests until we reach a stable test suite?
I'm not a big fan of waiting for a big pull request like #31 - taking advantages of baby steps seems to be more effective in cases like this.
What do you think?

**Comment by erickwilder** [comment]
Oh! And I'm fine to merge this one as is.

**Comment by abdulhaq-e** [comment]
> should we start by making tests pass with the current implementation or send new pull requests with 1.0-compliant code ignoring unrelated tests until we reach a stable test suite?
> I'm not a big fan of waiting for a big pull request like #31 - taking advantages of baby steps seems to be more effective in cases like this.

I modified the code to become compliant with 1.0 specifications and modified the tests along with it. Unfortunately, I couldn't do it through a step-by-step approach, i.e. a branch/commit for each "feature" because the change is large. I will have a pull request ready in a few days.

**Comment by jwhitlock** [comment]
Baby steps is OK with me, especially since I don't have the bandwidth for the 1.0 conversion either.

**Pull request merged**
